@extends('master')
@section('pageContent')

<div class="row">
<div class="col-sm-1"></div>

<div class="col-sm-8">

<div class="row">
<div class="heading">In Uttarakhand, a Wi-Fi collaboration project becomes a symbol of hope for a remote village.</div>
<div class="col-sm-12" style="text-align:justify">
The dimly-lit community service centre, with bare minimum furniture and dull green walls, houses the most important equipment that Gajiwali village in Uttarakhand’s Haridwar district has seen in recent years — a laptop. Its terrace holds equally significant technology: a seven-foot long pole protruding from two silver handle-like structures. That pole, part of a Wi-Fi tower (two more are to come up in this village), has ensured that Gajiwali is among the first villages in the hill state to benefit from a digitisation drive, a collaboration between the Centre and state government, and has become a symbol of hope for many youth living here at the foot of the Himalayas.<br /><br />
The village is part of a pilot project undertaken by the Department of Telecom and the Uttarakhand government to converge their respective schemes and ensure that they reach those who need it most, while cutting down on red tape. “With Wi-Fi up and running, I get faster speeds than I used to on the broadband. Apart from this, it is great to be part of change as it is through me that the villagers will get their passwords for the Wi-Fi,” says Kamal Singh Rawat, the community centre in charge, who has become an “important” person since November 4 — when Gajiwali became Wi-Fi enabled. Rawat is a village level entrepreneur (VLE) who survives on the commission he gets from the government for facilitation of online services, such as helping villagers obtain caste certificates, marriage certificates, ration cards or Adhaar cards.<br /><br />
For a village that does not even have a computer to boast about among 2,500 households, the Wi-Fi service is being seen as a sign of the changing times. “Competition stares you in the face whenever you go out of the village. We do not even have a decent computer lab and never had one when we were in school. So there is a natural inferiority complex when we go out to seek admission. Other kids outside learn things on the Internet that we are clueless about,” says Manjeet Pal, 22, who is pursuing diploma in civil engineering from a government polytechnic.<br /><br />
“I still don’t understand its meaning,” admits Dharam Pal, a construction site labourer, but adds, “This is something these young people are excited about. They say my kids would have the chance to compete with private school students in the future through this tower.”
Ram Avtar, a civil engineering student of a government polytechnic in Uttarkashi, is yet another student excited about the project. He aspires to become a junior engineer like two other residents of the village who had gone on to become “babus”. “The two babus from the village are cited as examples in every household in the village. Our village is marred by unemployment and lack of proper education. Our way out of poverty is only through education. The only decent library is miles away in Haridwar and, lack of uninterrupted Internet connection prevents us from using the smartphones for learning,” explains Avtar.<br /><br />
Most of the youngsters say they do not want to end up like their parents who either work in small shops in Haridwar, the closest town, or are labourers on construction sites. The Wi-Fi, the residents hope, will offset another problem here. “Mobile connectivity is poor and we have limited recharge options. Most of us do not have money to recharge phones as we are still students. Right now we are surviving on free data offered to us by a telecom giant,” says 24-year-old Harish Kumar, a graduate from Hemvati Nandan Bahuguna Garhwal University.
Perhaps more importantly, if the digitisation drive is extended to the Adarsh Sankul Vidyalaya, the only government primary school in the village, it might prevent children from dropping out early, says Kusum Sharma, the school in-charge for the last eight years. “If we can get one computer and Wi-Fi, not only the kids of labourers but others would also come. It would give a feeling of inclusiveness to these children. Teaching has changed. My daughter works in Delhi and she has sent me videos of private school teachers educating young ones through graphics, cartoons and other such techniques. What chance do these poor kids have against those? There is no level playing field when they go out and this is one of the reasons why most of them drop out early,” she adds.<br /><br />
The facility is now also being used by some of the villagers, mostly the youth, to overcome the challenges of demonetisation. “My parents used to wonder why I needed a smart phone. Phone call ke liye hi to lena hai… smartphone kyun chahiye (You need a phone to make calls then why do you need a smartphone)? With demonetisation, they now know we have to do transactions online. Now, they are slightly understanding of why we need Internet and smartphones. Yet, many are afraid of net banking frauds and are thus queuing up before banks.
With high speed Internet, we won’t mind using netbanking for the little money we have,” says Kapil Pal, a student pursuing civil engineering.<br /><br />
The state was brought into the digitisation loop by Ashish Joshi, the Controller of Communications, DoT, Uttarakhand. “Many central government schemes go unimplemented in the states. So we decided to converge the state and central schemes. We had the funds and technology to lay the optical fibre network but we needed space to put our equipment. Villagers and the Uttarakhand chief secretary agreed to lend a hand by providing facility centres. The state’s role is to now give out coupons with the Wi-Fi passwords, which are handed out by the village-level entrepreneur. The coupons cost Rs 23 for six hours and the speed of the net is 100 mbps,” says Joshi who believes that better internet connectivity would ease the life of the villagers as there are very few bank branches near the village. “And even if you find one, it is hard to get cash. The least we could do is to provide them facility of transacting online. Sooner or later they will accept the new ways of transaction,” Joshi adds.<br /><br />
Despite the initiative to bring Wi-Fi to the doorsteps of the villagers, efforts to make it part of their daily routine is still a challenge. “The VLEs need to encourage people to use the facility. Without it, the project’s aim will be defeated. If you make it tough to access technology, people will avoid using it. The state has to train more VLEs,” says a senior government official.
Joshi too admits there are shortcomings in the project despite its implementation going on in full swing. “A simple explanation is: supply side has been divided into three sets of initiatives. The first is digital infrastructure but we also need IT value additions in the form of apps, software etc. The second set is content that needs to be relevant to the citizens, ie, it should be in the local language. The third set is capacity. Unless we have the all these three sets (infrastructure, content, capacity), we won’t be able to meet the supply commence rate of the demand. The reason I have separated them into these three groups is because they are different departments with different sets of issues — both policy issues as well as operational concerns. Hence, it has become imperative for the success of Digital India that there is convergence and it needs to translate through merger of Departments of Telecom, IT and I&B,” says Joshi.
http://indianexpress.com/article/india/mountain-connect-uttarakhand-wifi-collaboration-gajiwali-4485133/

</div>
</div>
</div>
</div>

@endsection